<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Prism.Core" Version="9.0.537" />
        <PackageReference Include="Prism.Unity" Version="9.0.537" />
        <PackageReference Include="HandyControl" Version="3.5.1" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.15" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\VM.Halcon\VM.Halcon.csproj" />
        <ProjectReference Include="..\VM.IPlugin\VM.IPlugin.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="halcondotnet">
        <HintPath>..\HalconDll\halcondotnet.dll</HintPath>
      </Reference>
        <Reference Include="GongSolutions.WPF.DragDrop">
            <HintPath>..\..\03ThirdPartyDll\GongSolutions.WPF.DragDrop\GongSolutions.WPF.DragDrop.dll</HintPath>
        </Reference>
    </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="copy $(TargetPath) $(SolutionDir)\Modules\$(TargetFileName) /Y" />
    </Target>

</Project>
