<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="jacobslusser.ScintillaNET" Version="3.6.3" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\VM.Halcon\VM.Halcon.csproj" />
        <ProjectReference Include="..\VM.IPlugin\VM.IPlugin.csproj" />
          <ProjectReference Include="..\DemoThemes\DemoThemes.csproj" PrivateAssets="all" IncludeAssets="compile;build" ExcludeAssets="runtime;contentFiles" />
          <ProjectReference Include="..\VM.Shard\VM.Shard.csproj" />        
    </ItemGroup>
    <ItemGroup>
      <Reference Include="halcondotnet">
        <HintPath>..\Plugin.GrabImage\bin\Debug\net6.0-windows\halcondotnet.dll</HintPath>
      </Reference>
      <Reference Include="hdevenginedotnet">
        <HintPath>..\Plugin.GrabImage\bin\Debug\net6.0-windows\hdevenginedotnet.dll</HintPath>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Properties\DesignTimeResources.xaml">
        <ContainsDesignTimeResources>true</ContainsDesignTimeResources>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Helpers\" />
    </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="copy $(TargetPath) $(SolutionDir)\Modules\$(TargetFileName) /Y" />
    </Target>
</Project>
