<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>      <TargetFramework>net6.0-windows</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      
  </PropertyGroup>

  <ItemGroup>
    <None Update="Themes\Basic\Animations.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Basic\Colors.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Basic\ControlBasic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Basic\Dark.Color.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Basic\Font.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Basic\Geometry.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Basic\Light.Color.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\AlarmBar.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\AutoPropertyGrid.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\DateRangePicker.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\GenericPropertyEditor.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\ModernNumericInput.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\ModernWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\PasswordBoxEx.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\StatusIndicator.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Control\TimePick.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\Button\ButtonStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\CheckBox\CheckBoxStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\ComboBox\ComboBoxStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\Expander\ExpanderStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\Label\LabelStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\Scroll\ScrollStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\Shared\HeadStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\TextBox\TextBoxStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Themes\Style\ToggleButton\ToggleButtonStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Service\" />
  </ItemGroup>

</Project>
