<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Prism.Core" Version="9.0.537" />
        <PackageReference Include="Prism.Unity" Version="9.0.537" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="GongSolutions.WPF.DragDrop">
        <HintPath>..\..\03ThirdPartyDll\GongSolutions.WPF.DragDrop\GongSolutions.WPF.DragDrop.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
